---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  yaml: ./tasks/yaml.yml
  cpp: ./tasks/cpp.yml

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean the project
    silent: true
    deps:
      - cpp:clean
    cmds: []

  build:
    desc: Build the project
    silent: true
    deps:
      - cpp:build
    cmds: []

  test:
    desc: Test the project
    silent: true
    deps:
      - cpp:test
    cmds: []

  check:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - yaml:check
      - cpp:check
    cmds: []

  format:
    desc: Fix linting/formatting errors
    silent: true
    aliases:
      - fmt
    deps:
      - yaml:format
      - cpp:format
    cmds: []
